Repository Globalnomad-17/team17-globalnomad, pull requests merged in 2024-06, with the labels that each got.

#32 28 feat 내 정보 페이지 제작
  pages/SignupPage/sighup.tsx
  pages/myPage/index.tsx
  public/icons/myActivities.svg
  public/icons/myInfo.svg
  public/icons/myReservationCheck.svg
  public/icons/myReservationList.svg
  public/icons/profileModifyIcon.svg
  public/images/defaultProfileImage.png
  public/images/image.png
  src/Components/ProfileModify/ProfileModify.tsx
  tailwind.config.js
Labels: Feat

#34 28 feat 내 정보 페이지 제작
  pages/_document.tsx
  pages/index.tsx
  pages/my-page/index.tsx
  pages/myPage/index.tsx
  src/Components/Input/input.tsx
  src/Components/ProfileModify/ProfileModify.tsx
  src/service/users/users.queryOption.ts
  src/service/users/users.service.ts
  src/service/users/users.type.ts
Labels: Refactor

#38 2 feat 메인화면 제작
  package-lock.json
  package.json
  pages/MainPage/index.tsx
  pages/_app.tsx
  public/icons/StarOffIcon.svg
  public/icons/bedIcon.svg
  public/icons/filterIcon.svg
  public/icons/leftArrowActiveIcon.svg
  public/icons/leftArrowDefaultIcon.svg
  public/icons/leftArrowIcon.svg
  public/icons/leftArrowVariant1Icon.svg
  public/icons/noResultIcon.svg
  public/icons/paginationLeftArrowIcon.svg
  public/icons/paginationNextIcon.svg
  public/icons/paginationPrevIcon.svg
  public/icons/paginationRightArrowIcon.svg
  public/icons/rightArrowActiveIcon.svg
  public/icons/rightArrowDefaultIcon.svg
  public/icons/rightArrowVariant1Icon.svg
  public/icons/starIcon.svg
  public/icons/starOnIcon.svg
  public/images/HotAirBalloonImage.png
  public/images/StreetDanceImage.png
  public/images/noData.png
  public/images/steppingStoneImage.png
  src/Components/MainPage/ActivitiesList/SearchActivitiesHeader.tsx
  src/Components/MainPage/ActivitiesList/index.tsx
  src/Components/MainPage/Apis/Get/GetActivities.tsx
  src/Components/MainPage/Apis/axios.tsx
  src/Components/MainPage/Banner/index.tsx
  src/Components/MainPage/CategoryFilter/index.tsx
  src/Components/MainPage/Common/Button/BaseButton.tsx
  src/Components/MainPage/Common/CardResource/index.tsx
  src/Components/MainPage/Common/Category/index.tsx
  src/Components/MainPage/Common/DropdownMenu/index.tsx
  src/Components/MainPage/Common/Filter/Filter.tsx
  src/Components/MainPage/Common/Filter/FilterDropdown.tsx
  src/Components/MainPage/Common/MainLayout/index.tsx
  src/Components/MainPage/Common/Pagination/index.tsx
  src/Components/MainPage/Common/Search/index.tsx
  src/Components/MainPage/Common/Skeleton/index.tsx
  src/Components/MainPage/Constants/ImportImages.tsx
  src/Components/MainPage/Function/Throttle.tsx
  src/Components/MainPage/Hooks/useOutsideClick.ts
  src/Components/MainPage/Hooks/useResponsiveSize.ts
  src/Components/MainPage/Hooks/useToggleButton.ts
  src/Components/MainPage/PopularActivitiesList/index.tsx
  src/Components/MainPage/Stores/Activities.tsx
  src/Components/MainPage/Types/Activities.tsx
  src/Components/MainPage/index.tsx
  src/apis/get/getActivities/index.ts
  tsconfig.json
Labels: Feat

#33 feat: 예약내역(미완성)
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/my-page/index.tsx
  pages/my-page/reservations/index.tsx
  pages/signup/index.tsx
  pages/test/index.tsx
  public/icons/ArrowDown.svg
  public/icons/noReservation.svg
  src/Components/Modal/ModalReservationCancel.tsx
  src/Components/Modal/ModalReview.tsx
  src/Components/MyReservation/NoReservationList.tsx
  src/Components/MyReservation/ReservationFilter.tsx
  src/Components/MyReservation/ReservationList.tsx
  src/Components/MyReservation/ReservationStatus.tsx
  src/Components/ProfileModify/ProfileModify.tsx
  src/apis/myReservation/myReservation.tsx
  src/apis/myReservation/myReservation.type.ts
  src/constants/reservation.ts
  src/hooks/useModal.ts
  src/layouts/MyPageLayour.tsx
  src/service/auth/auth.type.ts
  src/service/myReservations/reservations.queryOption.ts
  src/service/myReservations/reservations.service.ts
  src/service/myReservations/reservations.type.ts
  src/service/myReservations/useReservationsService.ts
  tailwind.config.js
Labels: Feat

#52 feat: 미들웨어
  middleware.ts
Labels: Feat

#70 refactor: 예약현황 내 체험 관리 리팩토링
  pages/activity-details/[id]/index.tsx
  pages/my-page/activities/index.tsx
  pages/my-page/index.tsx
  pages/my-page/reservations/index.tsx
  src/Components/MyActivities/MyActivitiesList.tsx
  src/Components/MyPage/MobileDropDown.tsx
  src/Components/MyReservation/ReservationFilter.tsx
  src/Components/MyReservation/ReservationList.tsx
  src/Components/MyReservation/ReservationStatus.tsx
  src/Components/ProfileModify/ProfileModify.tsx
  src/Components/ReservationStatus/ReservationStatus.tsx
  tailwind.config.js
Labels: Refactor

#67 41 refactor 메인화면 제작
  public/icons/closeIcon.svg
  public/icons/searchIcon.svg
  public/images/HotAirBalloonImage.png
  public/images/PlanTravelImage.png
  public/images/WithTogetherImage.png
  public/images/steppingStoneImage.png
  src/Components/MainPage/ActivitiesList/SearchActivitiesHeader.tsx
  src/Components/MainPage/ActivitiesList/index.tsx
  src/Components/MainPage/Banner/index.tsx
  src/Components/MainPage/CategoryFilter/index.tsx
  src/Components/MainPage/Common/Button/BaseButton.tsx
  src/Components/MainPage/Common/CardResource/index.tsx
  src/Components/MainPage/Common/MainLayout/index.tsx
  src/Components/MainPage/Constants/ImportImages.tsx
  src/Components/MainPage/PopularActivitiesList/index.tsx
  tailwind.config.js
Labels: Refactor

#72 refactor: 예약내역 무한스크롤 에러 수정
  pages/auth/sign-up/index.tsx
  pages/my-page/reservations/index.tsx
Labels: Refactor

#75 feat: 예액내역, 내 체험 관리 스켈레톤
  pages/my-page/activities/index.tsx
  pages/my-page/reservations/index.tsx
  src/Components/MyActivities/MYactivitiesSkeleton.tsx
  src/Components/MyReservation/NoReservationList.tsx
  src/Components/MyReservation/ReservationSkeleton.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: Feat, Refactor

#82 feat: 메타태그, 마이페이지 리팩토링
  pages/activity-details/[id]/index.tsx
  pages/auth/sign-in/index.tsx
  pages/auth/sign-up/index.tsx
  pages/index.tsx
  pages/my-page/activities/index.tsx
  pages/my-page/index.tsx
  pages/my-page/reservations/index.tsx
  src/Components/ActivityDetails/ActivityContent.tsx
  src/Components/ActivityDetails/ActivityOverview.tsx
  src/Components/ActivityDetails/ActivityOverviewHeader.tsx
  src/Components/ActivityDetails/ReservationBox.tsx
  src/Components/ActivityEdit/ActivityEditForm.tsx
  src/Components/ActivityRegist/ActivityRegistForm.tsx
  src/Components/Common/HeadMeta.tsx
  src/Components/Modal/ModalReview.tsx
  src/Components/MyPage/MobileImageChange.tsx
  src/Components/MyReservation/NoReservationList.tsx
  src/Components/MyReservation/ReservationFilter.tsx
  src/Components/ReservationStatus/ReservationStatus.tsx
  src/Components/Toast/ToastUi.tsx
  src/constants/metaTag.tsx
  src/context/Authcontext.tsx
  src/layouts/MyPageLayour.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: Refactor

#86 41 refactor 메인화면 리팩토링
  public/icons/downArrowDefaultIcon.svg
  src/Components/MainPage/Banner/index.tsx
  src/Components/MainPage/Common/CardResource/index.tsx
  src/Components/MainPage/Common/Category/index.tsx
  src/Components/MainPage/Common/DropdownMenu/index.tsx
  src/Components/MainPage/Common/Filter/Filter.tsx
  src/Components/MainPage/Common/Filter/FilterDropdown.tsx
  src/Components/MainPage/Common/Pagination/index.tsx
  src/Components/MainPage/Common/Search/index.tsx
  src/Components/MainPage/Constants/ImportImages.tsx
  src/Components/MainPage/index.tsx
Labels: Refactor

#87 78 refactor 프로젝트 전반적인 수정
  pages/my-page/index.tsx
  src/Components/Common/LoginHeader/LoginHeaderDropdown.tsx
  src/Components/MyPage/MyPageSkeleton.tsx
  src/Components/ProfileModify/ProfileModify.tsx
  src/Components/ProfileModify/ProfileModifySkeleton.tsx
  src/Components/Toast/ToastUi.tsx
  src/service/activities/activities.queryOption.ts
  src/service/auth/auth.queryOption.ts
  src/service/myActivities/myActivities.queryOption.ts
  src/service/myNotifications/notifications.queryOption.ts
  src/service/myReservations/reservations.queryOption.ts
  src/service/users/users.queryOption.ts
Labels: Refactor

#91 Refactor : 배너 이미지 수정
  public/images/MilkyWayImage.png
  public/images/PlanTravelImage.png
  public/images/WithTogetherImage.png
  src/Components/MainPage/Constants/ImportImages.tsx
Labels: Refactor

#94 refactor: 이미지 최신화
  pages/auth/sign-in/index.tsx
  public/favicon.ico
  src/Components/Common/LoginHeader/LoginHeader.tsx
  src/Components/Common/LoginHeader/LoginHeaderDropdown.tsx
  src/Components/Common/LoginHeader/LoginHeaderDropdownSkeleton.tsx
  src/Components/Common/LoginHeader/NotificationBox.tsx
  src/Components/MyPage/MobileImageChange.tsx
  src/Components/ProfileModify/ProfileModify.tsx
  src/constants/user.ts
Labels: Refactor

#98 93 refactor 메인페이지 리팩토링
  src/Components/MainPage/ActivitiesList/index.tsx
  src/Components/MainPage/Banner/index.tsx
  tailwind.config.js
Labels: Refactor

#99 92 refactor 전반적인 css 수정
  pages/test/index.tsx
  src/Components/ActivityEdit/ActivityEditSchedule.tsx
  src/Components/ActivityEdit/EditCalendar.tsx
  src/Components/Common/LoginHeader/LoginHeader.tsx
  src/Components/Common/LoginHeader/LoginHeaderDropdownSkeleton.tsx
  src/Components/MyReservation/ReservationStatus.tsx
Labels: Refactor

#100 93 refactor 메인페이지 리팩토링
  src/Components/MainPage/Common/Category/index.tsx
  src/Components/MainPage/Common/Filter/Filter.tsx
Labels: Refactor
